/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * lab3JPanel.java
 *
 * Created on 06.12.2011, 13:33:12
 */
package ecolabs.labs.lab3;

import ecolabs.EcolabsView;
import ecolabs.labs.ScreenJPanel;

/**
 *
 * @author Ск
 */
public class Lab3JPanel extends ScreenJPanel {
    /**
     * Диаметр циклона. 1.N
     */
    double D;
    /**
     * Скорость движения газа
     */
    double ω;
    /**
     * средний размер частиц пыли, улавливаемых на 50 %, мкм;
     */
    double d;
    /**
     * коэффициент, учитывающий тип циклона;
     */
    double k = 41.4f;
    /**
     * вязкость газа, Па*c;
     */
    double μ = 22.2e-6f;
    /**
     * плотность пылевых частиц, кг/м3.
     */
    double ρ = 2150;
    
    /**
     * Расчет минимального размера частиц пыли, улавливаемых циклоном
     */
    private double d_min(double D, double ω){
        return (d*k*1000*Math.sqrt(1000*μ/(ρ*ω)));
    }

    public Lab3JPanel(EcolabsView parent) {
        super(parent);
        initComponents();
        Title = "Лабораторная работа №3";
        Caption = "Определение минимального размера частиц пыли,улавливаемых циклоном";        
        
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ecolabs.EcolabsApp.class).getContext().getResourceMap(Lab3JPanel.class);
        String pattern = resourceMap.getString("jLabelVarInfo.text");
        jLabelVarInfo.setText(String.format(pattern, D,ω,d,k,μ,ρ));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxVar18 = new javax.swing.JComboBox();
        jLabelVar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelVarInfo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setName("Form"); // NOI18N

        jComboBoxVar18.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1" }));
        jComboBoxVar18.setName("jComboBoxVar18"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ecolabs.EcolabsApp.class).getContext().getResourceMap(Lab3JPanel.class);
        jLabelVar.setText(resourceMap.getString("jLabelVar.text")); // NOI18N
        jLabelVar.setName("jLabelVar"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jLabelVarInfo.setText(resourceMap.getString("jLabelVarInfo.text")); // NOI18N
        jLabelVarInfo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelVarInfo.setName("jLabelVarInfo"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelVarInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelVarInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
        );

        jPanel2.setName("jPanel2"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelVar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxVar18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVar)
                    .addComponent(jComboBoxVar18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxVar;
    private javax.swing.JComboBox jComboBoxVar1;
    private javax.swing.JComboBox jComboBoxVar10;
    private javax.swing.JComboBox jComboBoxVar11;
    private javax.swing.JComboBox jComboBoxVar12;
    private javax.swing.JComboBox jComboBoxVar13;
    private javax.swing.JComboBox jComboBoxVar14;
    private javax.swing.JComboBox jComboBoxVar15;
    private javax.swing.JComboBox jComboBoxVar16;
    private javax.swing.JComboBox jComboBoxVar17;
    private javax.swing.JComboBox jComboBoxVar18;
    private javax.swing.JComboBox jComboBoxVar2;
    private javax.swing.JComboBox jComboBoxVar3;
    private javax.swing.JComboBox jComboBoxVar4;
    private javax.swing.JComboBox jComboBoxVar5;
    private javax.swing.JComboBox jComboBoxVar6;
    private javax.swing.JComboBox jComboBoxVar7;
    private javax.swing.JComboBox jComboBoxVar8;
    private javax.swing.JComboBox jComboBoxVar9;
    private javax.swing.JLabel jLabelVar;
    private javax.swing.JLabel jLabelVarInfo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
